# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "AppVersion올리기"
lane :set_version do |options|
  case options[:version]
  when "major", "minor", "patch"
    increment_version_number(bump_type: options[:version],
			     xcodeproj: "./Healthy/Healthy/Healthy.xcodeproj")
  else
    increment_version_number(version_number: options[:version],
			     xcodeproj: "./Healthy/Healthy/Healthy.xcodeproj")
  end
  
  # 가장 흔한 빌드번호 규칙은, 특정 버전번호에 해당하는 n번째 빌드의 빌드번호는 n이어야 한다는 것이다. 
  # 하지만 자동화 과정에서는 이 규칙을 적용 할 수 없으므로, 현재시간을 조합하여 중복될 일 없는 빌드번호를 만든다.
  increment_build_number(
    build_number: Time.new.strftime("%Y.%m%d.%H%M"), # 2021년 4월 17일 14시 53분 -> 2021.0417.1453
    xcodeproj: "./Healthy/Healthy/Healthy.xcodeproj" 
    )
  version_number = "#{lane_context[SharedValues::VERSION_NUMBER]}(#{lane_context[SharedValues::BUILD_NUMBER]})"
  commit_version_bump(
    message: "Update version - #{version_number}",
    xcodeproj: "./Healthy/Healthy/Healthy.xcodeproj"
    )
  add_git_tag(tag: "v#{version_number}")
  push_to_git_remote
end


lane :release do
  # 5. keychain 초기화 🔑
  create_keychain(
    name: ENV["KEYCHAIN_NAME"],
    password: ENV["KEYCHAIN_PASSWORD"],
    timeout: 1800,
    default_keychain: true,
    unlock: true,
    lock_when_sleeps: false
  )

  app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

  # 6. match를 실행하여 인증서 및 프로파일 불러오기 ✍🏼
  match(
    git_url: "git@github.com:cheonsong/Healthy.git",
    storage_mode: "git",
    type: "appstore",
    readonly: true,
    keychain_name: ENV["KEYCHAIN_NAME"],
    keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

  # 7. 빌드 및 내보내기 🏗
  gym(
    workspace: "Healthy.xcworkspace",
    scheme: "Healthy",
    configuration: "Release",
    export_options: {
      method: "app-store",
      signingStyle: "manual"
    }
    )

  # 8. 앱스토어 업로드 🎉
  deliver(
    submit_for_review: false,
    force: true,
    skip_screenshots: true,
    automatic_release: true,
    precheck_include_in_app_purchases: false,
    copyright: "© #{Time.now.year} cheonsong, Inc.",
    submission_information: {    
      export_compliance_encryption_updated: false,
      export_compliance_uses_encryption: false,
      add_id_info_uses_idfa: false
      }
    )
end

# lane이 모두 완료된 뒤 호출됨
after_all do |lane|
  # 9. 배포 결과 슬랙 노티 🚨
  slack(
      message: "Testflight 배포에 성공했습니다!",
      slack_url: "https://hooks.slack.com/services/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"
    )
end

# 에러 발생 시 호출 됨
error do |lane, exception|
  slack(
      message: "에러 발생 : #{exception}",
      success: false,
      slack_url: "https://hooks.slack.com/services/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"
    )
end

end
