# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "AppVersion올리기"
lane :set_version do |options|
  case options[:version]
  when "major", "minor", "patch"
    increment_version_number(bump_type: options[:version])
  else
    increment_version_number(version_number: options[:version])
  end
  
  # 가장 흔한 빌드번호 규칙은, 특정 버전번호에 해당하는 n번째 빌드의 빌드번호는 n이어야 한다는 것이다. 
  # 하지만 자동화 과정에서는 이 규칙을 적용 할 수 없으므로, 현재시간을 조합하여 중복될 일 없는 빌드번호를 만든다.
  increment_build_number(
    build_number: Time.new.strftime("%Y.%m%d.%H%M") # 2021년 4월 17일 14시 53분 -> 2021.0417.1453
    )
  version_number = "#{lane_context[SharedValues::VERSION_NUMBER]}(#{lane_context[SharedValues::BUILD_NUMBER]})"
  commit_version_bump(
    message: "Update version - #{version_number}"
    )
  add_git_tag(tag: "v#{version_number}")
  push_to_git_remote
end
end
