# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "AppVersion올리기"
lane :upload do |options|
  case options[:version]
  when "major", "minor", "patch"
    increment_version_number(bump_type: options[:version],
			     xcodeproj: "./Healthy/Healthy/Healthy.xcodeproj")
  else
    increment_version_number(version_number: options[:version],
			     xcodeproj: "./Healthy/Healthy/Healthy.xcodeproj")
  end
  
  # 빌드 번호 올리기
  increment_build_number(xcodeproj: "./Healthy/Healthy/Healthy.xcodeproj", build_number: latest_testflight_build_number + 1)

  # 5. 매치 인증서 확인
  match(
    type: "appstore"
    )

  # 7. 빌드 및 내보내기 🏗
build_app(
  scheme: "Healthy",
  export_method: "app-store",
)

  build_app(workspace: "Healthy.xcworkspace", scheme: "Healthy", configuration: "Release")

  # 8. 앱스토어 업로드 🎉
  upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  
end

# lane이 모두 완료된 뒤 호출됨
after_all do |lane|
  # 9. 배포 결과 슬랙 노티 🚨
  slack(
      message: "Testflight 배포에 성공했습니다!",
      slack_url: "https://hooks.slack.com/services/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"
    )
end

# 에러 발생 시 호출 됨
error do |lane, exception|
  slack(
      message: "에러 발생 : #{exception}",
      success: false,
      slack_url: "https://hooks.slack.com/services/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"
    )
end

end
